version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Ensure this is a clean volume

  python-app:
    build: ./backend
    container_name: python_container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    ports:
      - "5002:5000"
    volumes:
      - ./backend:/app

volumes:
  mysql_data:
